#!/usr/bin/env node
/**
 * module-graph — regenerate the module dependency diagram in README.md.
 *
 *   node scripts/module-graph.mjs           # rewrite the block in README.md
 *   node scripts/module-graph.mjs --check   # exit 1 if the README block is stale (CI-friendly)
 *   node scripts/module-graph.mjs --print   # write nothing, print the Mermaid block
 *
 * WHY THIS EXISTS AND NOT A PLUGIN. `dev.iurysouza:modulegraph` was evaluated for exactly this job
 * on 2026-08-27 and rejected. It is a single-maintainer Gradle plugin, last released 2025-10-14,
 * which would have had to be verified against Gradle 9.7.0 and then kept working across every
 * toolchain move. The whole task is reading `include(...)` out of settings.gradle.kts and
 * `project(":x")` out of each build file. That is this script, and it has no dependency, no plugin
 * to apply, and nothing to break when AGP moves.
 *
 * graphify was checked first, as the adoption plan required: it models symbols and call flow, not
 * Gradle module wiring, so it does not answer this question either.
 *
 * Deliberately NOT a Gradle task: this must run without configuring the build, so it stays usable
 * in a docs job that has no JDK warm and cannot afford a configuration phase.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)))
const README = join(ROOT, 'README.md')
const BEGIN = '<!-- module-graph:begin -->'
const END = '<!-- module-graph:end -->'
const args = process.argv.slice(2)

const modules =
  (readFileSync(join(ROOT, 'settings.gradle.kts'), 'utf8').match(/^include\("([^"]+)"\)/gm) ?? [])
    .map((line) => line.match(/"([^"]+)"/)[1].replace(/^:/, ''))

// Mermaid node ids cannot contain ':', which every nested module path uses.
const id = (m) => m.replace(/[:/-]/g, '_')

const edges = []
for (const m of modules) {
  const buildFile = join(ROOT, m.replace(/:/g, '/'), 'build.gradle.kts')
  if (!existsSync(buildFile)) continue
  const text = readFileSync(buildFile, 'utf8')
  for (const dep of text.matchAll(/project\("(:[^"]+)"\)/g)) {
    const target = dep[1].replace(/^:/, '')
    // A module listing itself would render a self-loop; a dependency on something not in
    // settings.gradle.kts is a real bug worth surfacing rather than silently drawing.
    if (target === m) continue
    if (!modules.includes(target)) {
      console.error(`  WARN ${m} depends on :${target}, which settings.gradle.kts does not include`)
      continue
    }
    edges.push([m, target])
  }
}

const lines = [
  BEGIN,
  `<!-- generated by scripts/module-graph.mjs - do not hand-edit inside these markers -->`,
  '',
  '```mermaid',
  'graph LR',
  ...edges.map(([a, b]) => `  ${id(a)}["${a}"] --> ${id(b)}["${b}"]`),
  '```',
  '',
  `_${modules.length} modules, ${edges.length} internal dependencies._`,
  END,
].join('\n')

if (args.includes('--print')) {
  console.log(lines)
  process.exit(0)
}

const readme = readFileSync(README, 'utf8')
const start = readme.indexOf(BEGIN)
const stop = readme.indexOf(END)
if (start === -1 || stop === -1) {
  console.error(`  README.md has no ${BEGIN} / ${END} markers. Add them where the diagram belongs.`)
  process.exit(1)
}
const next = readme.slice(0, start) + lines + readme.slice(stop + END.length)

if (args.includes('--check')) {
  if (next === readme) {
    console.log(`  [OK]   module graph current (${modules.length} modules, ${edges.length} edges)`)
    process.exit(0)
  }
  console.error('  [STALE] README module graph does not match the build files. Run without --check.')
  process.exit(1)
}

writeFileSync(README, next)
console.log(`  module graph written: ${modules.length} modules, ${edges.length} edges`)
